apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.vmName }}-root-disk
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass }}
