apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vm-boot-image
  namespace: vm-workloads
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: my-block-storage
