apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-net
  namespace: vm-workloads
spec:
  config: '{ "cniVersion": "0.3.1", "name":"macvlan-net", "type":"macvlan", "master":"eth0", "mode":"bridge", "ipam":{ "type":"host-local", "subnet":"192.168.100.0/24" } }'
