apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-root-disk
  namespace: vm-workloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: my-block-storage
